running build_ext
building 'utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/utils
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/numpy/core/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c utils/cython_bbox.c -o build/temp.linux-x86_64-3.7/utils/cython_bbox.o -Wno-cpp
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/utils
gcc -pthread -shared -B /usr/licensed/anaconda3/5.3.0/compiler_compat -L/usr/licensed/anaconda3/5.3.0/lib -Wl,-rpath=/usr/licensed/anaconda3/5.3.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/utils/cython_bbox.o -o build/lib.linux-x86_64-3.7/utils/cython_bbox.cpython-37m-x86_64-linux-gnu.so
building 'utils.cython_nms' extension
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/numpy/core/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c utils/cython_nms.c -o build/temp.linux-x86_64-3.7/utils/cython_nms.o -Wno-cpp
utils/cython_nms.c: In function ‘__pyx_pf_5utils_10cython_nms_2soft_nms’:
utils/cython_nms.c:3374:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_11 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
utils/cython_nms.c:3885:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_11 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
gcc -pthread -shared -B /usr/licensed/anaconda3/5.3.0/compiler_compat -L/usr/licensed/anaconda3/5.3.0/lib -Wl,-rpath=/usr/licensed/anaconda3/5.3.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/utils/cython_nms.o -o build/lib.linux-x86_64-3.7/utils/cython_nms.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/utils/cython_bbox.cpython-37m-x86_64-linux-gnu.so -> utils
copying build/lib.linux-x86_64-3.7/utils/cython_nms.cpython-37m-x86_64-linux-gnu.so -> utils
Compiling nms kernels by nvcc...
make.sh: line 20: nvcc: command not found
Including CUDA code.
/home/fhertan/mask-rcnn-videos/lib/model/nms
['/home/fhertan/mask-rcnn-videos/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmp8snkxhnr/_nms.c
setting the current directory to '/tmp/tmp8snkxhnr'
running build_ext
building '_nms' extension
creating home
creating home/fhertan
creating home/fhertan/mask-rcnn-videos
creating home/fhertan/mask-rcnn-videos/lib
creating home/fhertan/mask-rcnn-videos/lib/model
creating home/fhertan/mask-rcnn-videos/lib/model/nms
creating home/fhertan/mask-rcnn-videos/lib/model/nms/src
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c _nms.c -o ./_nms.o -std=c99
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c /home/fhertan/mask-rcnn-videos/lib/model/nms/src/nms_cuda.c -o ./home/fhertan/mask-rcnn-videos/lib/model/nms/src/nms_cuda.o -std=c99
gcc -pthread -shared -B /usr/licensed/anaconda3/5.3.0/compiler_compat -L/usr/licensed/anaconda3/5.3.0/lib -Wl,-rpath=/usr/licensed/anaconda3/5.3.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_nms.o ./home/fhertan/mask-rcnn-videos/lib/model/nms/src/nms_cuda.o /home/fhertan/mask-rcnn-videos/lib/model/nms/src/nms_cuda_kernel.cu.o -o ./_nms.so
gcc: error: /home/fhertan/mask-rcnn-videos/lib/model/nms/src/nms_cuda_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling roi pooling kernels by nvcc...
make.sh: line 30: nvcc: command not found
Including CUDA code.
/home/fhertan/mask-rcnn-videos/lib/model/roi_pooling
generating /tmp/tmp3nj4a2ob/_roi_pooling.c
setting the current directory to '/tmp/tmp3nj4a2ob'
running build_ext
building '_roi_pooling' extension
creating home
creating home/fhertan
creating home/fhertan/mask-rcnn-videos
creating home/fhertan/mask-rcnn-videos/lib
creating home/fhertan/mask-rcnn-videos/lib/model
creating home/fhertan/mask-rcnn-videos/lib/model/roi_pooling
creating home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c _roi_pooling.c -o ./_roi_pooling.o -std=c99
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c /home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src/roi_pooling.c -o ./home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src/roi_pooling.o -std=c99
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c /home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src/roi_pooling_cuda.c -o ./home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src/roi_pooling_cuda.o -std=c99
gcc -pthread -shared -B /usr/licensed/anaconda3/5.3.0/compiler_compat -L/usr/licensed/anaconda3/5.3.0/lib -Wl,-rpath=/usr/licensed/anaconda3/5.3.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_roi_pooling.o ./home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src/roi_pooling.o ./home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src/roi_pooling_cuda.o /home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src/roi_pooling.cu.o -o ./_roi_pooling.so
gcc: error: /home/fhertan/mask-rcnn-videos/lib/model/roi_pooling/src/roi_pooling.cu.o: No such file or directory
Traceback (most recent call last):
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 35, in <module>
    ffi.build()
  File "/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling roi crop kernels by nvcc...
make.sh: line 48: nvcc: command not found
Including CUDA code.
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop
generating /tmp/tmp4afnodxm/_roi_crop.c
setting the current directory to '/tmp/tmp4afnodxm'
running build_ext
building '_roi_crop' extension
creating home
creating home/fhertan
creating home/fhertan/mask-rcnn-videos
creating home/fhertan/mask-rcnn-videos/lib
creating home/fhertan/mask-rcnn-videos/lib/model
creating home/fhertan/mask-rcnn-videos/lib/model/roi_crop
creating home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c _roi_crop.c -o ./_roi_crop.o -std=c99
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c /home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c -o ./home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.o -std=c99
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBHWD_updateGradInput’:
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:190:14: warning: unused variable ‘inBottomRight’ [-Wunused-variable]
         real inBottomRight=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:189:14: warning: unused variable ‘inBottomLeft’ [-Wunused-variable]
         real inBottomLeft=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:188:14: warning: unused variable ‘inTopRight’ [-Wunused-variable]
         real inTopRight=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:187:14: warning: unused variable ‘inTopLeft’ [-Wunused-variable]
         real inTopLeft=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:186:14: warning: unused variable ‘v’ [-Wunused-variable]
         real v=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBCHW_updateGradInput’:
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:440:14: warning: unused variable ‘inBottomRight’ [-Wunused-variable]
         real inBottomRight=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:439:14: warning: unused variable ‘inBottomLeft’ [-Wunused-variable]
         real inBottomLeft=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:438:14: warning: unused variable ‘inTopRight’ [-Wunused-variable]
         real inTopRight=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:437:14: warning: unused variable ‘inTopLeft’ [-Wunused-variable]
         real inTopLeft=0;
              ^
/home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.c:436:14: warning: unused variable ‘v’ [-Wunused-variable]
         real v=0;
              ^
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c /home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop_cuda.c -o ./home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop_cuda.o -std=c99
gcc -pthread -shared -B /usr/licensed/anaconda3/5.3.0/compiler_compat -L/usr/licensed/anaconda3/5.3.0/lib -Wl,-rpath=/usr/licensed/anaconda3/5.3.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_roi_crop.o ./home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop.o ./home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop_cuda.o /home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o -o ./_roi_crop.so
gcc: error: /home/fhertan/mask-rcnn-videos/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
make.sh: line 57: nvcc: command not found
Including CUDA code.
/home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom/roi_align
generating /tmp/tmpe6cwlggr/_roi_align.c
setting the current directory to '/tmp/tmpe6cwlggr'
running build_ext
building '_roi_align' extension
creating home
creating home/fhertan
creating home/fhertan/mask-rcnn-videos
creating home/fhertan/mask-rcnn-videos/lib
creating home/fhertan/mask-rcnn-videos/lib/modeling
creating home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom
creating home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom/roi_align
creating home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom/roi_align/src
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c _roi_align.c -o ./_roi_align.o -std=c99
gcc -pthread -B /usr/licensed/anaconda3/5.3.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/licensed/anaconda3/5.3.0/include/python3.7m -c /home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom/roi_align/src/roi_align_cuda.c -o ./home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom/roi_align/src/roi_align_cuda.o -std=c99
gcc -pthread -shared -B /usr/licensed/anaconda3/5.3.0/compiler_compat -L/usr/licensed/anaconda3/5.3.0/lib -Wl,-rpath=/usr/licensed/anaconda3/5.3.0/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_roi_align.o ./home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom/roi_align/src/roi_align_cuda.o /home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom/roi_align/src/roi_align_kernel.cu.o -o ./_roi_align.so
gcc: error: /home/fhertan/mask-rcnn-videos/lib/modeling/roi_xfrom/roi_align/src/roi_align_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/fhertan/.local/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/licensed/anaconda3/5.3.0/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
